# feature extractor
fe:
  model_name: 'embedding_net_gt'
  load_pretrained: true
  optim: "none"  # none extra rl_loss  # optimize feature extractor with ril loss
  lr: 2e-4
  betas: [0.9, 0.999]
  update_frequency: 10 # 10
  update_after_steps: 10000 #10000
  weight_edge_loss: 0.3
  weight_side_loss: 10
  n_embedding_features: 16  # number of embedding feature channels
  n_raw_channels: 3  # number of channels in current state
  patch_shape: [180, 180]
  patch_stride: [90, 90]
  patch_manager: rotated
#  warmup:
#    n_iterations: 50  # number of iterations of feature extrqactor warmup
#    batch_size: 10  # batch size for feature extractor warmup


