sac:
  num_seed_steps: 0
  reg_scaler: 10
  discount: 0.99
  init_temperature: 0.1
  temperature_regulation: optimized #constant, follow_quality, optimized
  alpha_lr: 1e-3
  alpha_betas: [0.9, 0.999]
  actor_lr: 1e-4
  actor_betas: [0.9, 0.999]
  actor_update_frequency: 1
  critic_lr: 1e-4
  critic_betas: [0.9, 0.999]
  critic_tau: 0.005
  critic_target_update_frequency: 2
  batch_size: 10
  weight_tolerance_attr: 0.1
  weight_tolerance_rep: 0.9
  embeddings_lr: 2e-4
  embeddings_update_frequency: 200

  MC_DQL: false # monte carlo learning for the critic

  diag_gaussian_actor:
    log_std_bounds: [-5, 2]