trainer:
  # main training (env, trainer)
  T_max: 100000  # 100000 #Number of training steps
  t_max: 100  # Mem size
  data_update_frequency: 10
  post_stats_frequency: 10
  post_model_frequency: 100
  n_updates_per_step: 10
  max_episode_length: 1  # Maximum episode length
  batch_size: 20
  add_noise: false

