gen:
  algorithm: sac_seed_test_sg_global #Algorithm used for training
  master_port: !!str "12351" #port num on localhost for icp
  cross_validate_hp: false # make gridsearch cv of hp
  no_save: false #dont save models
  test_score_only: false #no learning only validation
  n_processes_per_gpu: 1 #Number of training async agents
  n_gpu: 1 #Number of gpus per process
  evaluate: false #evaluate existing model
  seed: 123 #Random seed. Not used is "seed_test" in general.algorithm
  target_dir: seed_test_sg2 # dir name in base-dir. Logs are in here
  base_dir: /g/kreshuk/hilt/projects/fewShotLearning/mutexWtsd # base-dir
  data_dir: /g/kreshuk/hilt/projects/fewShotLearning/mutexWtsd/data/storage/circles/pix_and_graphs
  # env and model defs
  model_name: 'agent_model'
  resume: false # resume from state dict model_name in base_dir
  # n_edge_features: 10 #number of initial edge features

